CREATE DATABASE tourism;
USE tourism;
CREATE TABLE hotel (hotel_id INT, name VARCHAR(50), address VARCHAR(100), city VARCHAR(50), state VARCHAR(50), pin_code VARCHAR(10), phone VARCHAR(10), email VARCHAR(50), rating INT, established_year INT);
INSERT INTO hotel VALUES(121,"Green Valley Inn","12 Lake View Road","Ooty","Tamil Nadu","643001", "9876501234", "contact@greenvalley.com", 4, 2015);
CREATE TABLE tourist_spot(spot_id INT, name VARCHAR(30),location VARCHAR(20),type VARCHAR(50),description VARCHAR(100),opening_time TIME,closing_time TIME,ticket_price DECIMAL(10,2),rating INT,established_year INT);
INSERT INTO tourist_spot VALUES(1,"Botanical Gardens","Ooty","Hill Station","Landscaped gardens featuring rare trees, a fern house & an Italian-style garden set in 55 acres",'07:00:00','18:30:00',50.00,5,1848);
INSERT INTO tourist_spot VALUES(1,"Botanical Gardens","Ooty","Hill Station","Landscaped gardens featuring rare trees, a fern house & an Italian-style garden set in 55 acres",'07:00:00','18:30:00',50.00,5,1848);
USE tourism;
CREATE TABLE travel_agency (agency_id INT, name VARCHAR(50), contact_person VARCHAR(50), phone VARCHAR(10), email VARCHAR(30), address VARCHAR(100), city VARCHAR(50), state VARCHAR(50), license_number VARCHAR(50), rating INT);
INSERT INTO travel_agency VALUES(1, "Hilltop Travels", "Suresh Kumar", "9123405678", "info@hilltop.com", "24 Gandhi Road", "Coimbatore", "Tamil Nadu", "LIC123456", 4);
CREATE TABLE booking (booking_id INT, booking_date DATE, customer_name VARCHAR(50), contact_number VARCHAR(10), hotel_id INT, spot_id INT, num_people INT, total_price DECIMAL(10,2), status VARCHAR(50), notes VARCHAR(500));
INSERT INTO booking VALUES (1, "2025-06-01", "Ravi", "9988776655", 1, 1, 3, 4500.00, "Confirmed", "Scenic mountain view");
CREATE TABLE transport (transport_id INT, company_name VARCHAR(50), vehicle_type VARCHAR(50), contact_number VARCHAR(10), price_per_km DECIMAL(10,2), available BOOLEAN, city VARCHAR(50), state VARCHAR(50), capacity INT, rating INT);
INSERT INTO transport VALUES (1, "Blue Hills Cabs", "Sedan", "9876512345", 18.50, TRUE, "Ooty", "Tamil Nadu", 4, 5);
CREATE TABLE tour_guide (guide_id INT, name VARCHAR(50), language VARCHAR(50), experience_years INT, contact_number VARCHAR(10), email VARCHAR(30), city VARCHAR(50), state VARCHAR(50), rating INT, fee_per_day DECIMAL(10,2));
INSERT INTO tour_guide VALUES (1, "Karthik", "Tamil", 6, "9123456780", "karthik@guide.com", "Ooty", "Tamil Nadu", 4, 1800.00);
CREATE TABLE review (review_id INT, tourist_name VARCHAR(50), rating INT, review_text VARCHAR(500), visit_date DATE, hotel_id INT, spot_id INT, guide_id INT, transport_id INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO review VALUES (1, "Anitha Menon", 4, "Nice experience overall, good climate and scenery.", "2025-06-01", 1, 1, 1, 1, CURRENT_TIMESTAMP);
CREATE TABLE payment (payment_id INT, booking_id INT, amount DECIMAL(10,2), payment_method VARCHAR(50), payment_date DATE, status VARCHAR(50), transaction_id VARCHAR(50), currency VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, notes VARCHAR(500));
INSERT INTO payment VALUES (1, 1, 4500.00, "UPI", "2025-06-01", "Completed", "TXN555666777", "INR", CURRENT_TIMESTAMP, "Smooth transaction");
ALTER TABLE hotel ADD COLUMN webiste VARCHAR(25);
ALTER TABLE hotel ADD COLUMN manger_name VARCHAR(30);
ALTER TABLE hotel ADD COLUMN star_rating INT;
ALTER TABLE hotel ADD COLUMN has_pool BOOLEAN;
ALTER TABLE hotel ADD COLUMN has_wifi BOOLEAN;
ALTER TABLE hotel DROP COLUMN pin_code, DROP COLUMN established_year;
ALTER TABLE hotel RENAME COLUMN name TO hotel_name, RENAME COLUMN phone TO contact_number,RENAME COLUMN city to location_city;
ALTER TABLE hotel CHANGE COLUMN email hotel_email VARCHAR(30),CHANGE state hotel_state VARCHAR(30),CHANGE COLUMN address hotel_address VARCHAR(100), CHANGE COLUMN rating stars INT, CHANGE COLUMN has_wifi wifi_availability BOOLEAN;
ALTER TABLE tourist_spot ADD COLUMN guide_availabilty BOOLEAN,ADD COLUMN photo_link VARCHAR(50),ADD COLUMN parking_available BOOLEAN, ADD COLUMN wheelchair_access BOOLEAN, ADD COLUMN spot_area VARCHAR(50);
ALTER TABLE tourist_spot DROP COLUMN established_year, DROP COLUMN rating;
ALTER TABLE tourist_spot RENAME COLUMN name TO spot_name, RENAME COLUMN type TO category, RENAME COLUMN location TO place;
ALTER TABLE tourist_spot CHANGE COLUMN ticket_price entry_fee DECIMAL(10,2), CHANGE COLUMN description details VARCHAR(500), CHANGE COLUMN spot_area area_size VARCHAR(50), CHANGE COLUMN place spot_location VARCHAR(100), CHANGE COLUMN opening_time open_from TIME;
ALTER TABLE tourist_spot CHANGE COLUMN spot_name spot_name VARCHAR(50);
ALTER TABLE travel_agency ADD COLUMN gst_number VARCHAR(50), ADD COLUMN branches INT, ADD COLUMN rating_status VARCHAR(50), ADD COLUMN head_office VARCHAR(50), ADD COLUMN support_email VARCHAR(30);
ALTER TABLE travel_agency DROP COLUMN state, DROP COLUMN license_number;
ALTER TABLE travel_agency RENAME COLUMN name TO agency_name, RENAME COLUMN phone TO mobile, RENAME COLUMN contact_person TO manager;
ALTER TABLE travel_agency CHANGE COLUMN city agency_city VARCHAR(50), CHANGE COLUMN rating stars INT, CHANGE COLUMN address agency_address VARCHAR(100), CHANGE COLUMN mobile contact_no VARCHAR(10), CHANGE COLUMN support_email help_email VARCHAR(30);
ALTER TABLE booking ADD COLUMN check_in DATE, ADD COLUMN check_out DATE, ADD COLUMN is_paid BOOLEAN, ADD COLUMN discount_applied BOOLEAN, ADD COLUMN booking_channel VARCHAR(50);
ALTER TABLE booking DROP COLUMN notes, DROP COLUMN contact_number;
ALTER TABLE booking RENAME COLUMN customer_name TO guest_name, RENAME COLUMN hotel_id TO stay_id, RENAME COLUMN spot_id TO destination_id;
ALTER TABLE booking CHANGE COLUMN status booking_status VARCHAR(50), CHANGE COLUMN total_price price_total DECIMAL(10,2), CHANGE COLUMN booking_channel channel_used VARCHAR(50), CHANGE COLUMN guest_name customer_fullname VARCHAR(50);
ALTER TABLE transport ADD COLUMN air_conditioned BOOLEAN, ADD COLUMN fuel_type VARCHAR(50), ADD COLUMN registration_number VARCHAR(50), ADD COLUMN driver_name VARCHAR(50), ADD COLUMN trip_count INT;
ALTER TABLE transport DROP COLUMN price_per_km, DROP COLUMN rating;
ALTER TABLE transport RENAME COLUMN company_name TO transport_name, RENAME COLUMN city TO service_city, RENAME COLUMN state TO service_state;
ALTER TABLE transport CHANGE COLUMN available is_available BOOLEAN, CHANGE COLUMN vehicle_type type VARCHAR(50), CHANGE COLUMN capacity seats INT, CHANGE COLUMN contact_number phone_no VARCHAR(10), CHANGE COLUMN service_city operating_city VARCHAR(50);
ALTER TABLE tour_guide ADD COLUMN rating_stars INT, ADD COLUMN badge_number VARCHAR(50), ADD COLUMN last_assigned DATE, ADD COLUMN languages_known VARCHAR(50), ADD COLUMN certification VARCHAR(50);
ALTER TABLE tour_guide DROP COLUMN state, DROP COLUMN experience_years;
ALTER TABLE tour_guide RENAME COLUMN name TO full_name, RENAME COLUMN language TO primary_language, RENAME COLUMN city TO hometown;
ALTER TABLE tour_guide CHANGE COLUMN contact_number phone VARCHAR(10), CHANGE COLUMN fee_per_day charges DECIMAL(10,2), CHANGE COLUMN email guide_email VARCHAR(30), CHANGE COLUMN certification certified_by VARCHAR(50), CHANGE COLUMN full_name guide_name VARCHAR(50);
ALTER TABLE review ADD COLUMN guide_rating INT, ADD COLUMN transport_rating INT, ADD COLUMN overall_feedback VARCHAR(500), ADD COLUMN images_url VARCHAR(50), ADD COLUMN reply VARCHAR(500);
ALTER TABLE review DROP COLUMN created_at, DROP COLUMN rating;
ALTER TABLE review RENAME COLUMN review_text TO comment, RENAME COLUMN tourist_name TO reviewer_name, RENAME COLUMN spot_id TO place_id;
ALTER TABLE review CHANGE COLUMN hotel_id hotel_ref INT, CHANGE COLUMN transport_id vehicle_id INT, CHANGE COLUMN reviewer_name user_name VARCHAR(50), CHANGE COLUMN visit_date visited_on DATE, CHANGE COLUMN place_id spot_ref INT;
ALTER TABLE payment ADD COLUMN is_refunded BOOLEAN, ADD COLUMN refund_amount DECIMAL(10,2), ADD COLUMN refunded_on DATE, ADD COLUMN verified_by VARCHAR(50), ADD COLUMN payment_note VARCHAR(500);
ALTER TABLE payment DROP COLUMN currency, DROP COLUMN status;
ALTER TABLE payment RENAME COLUMN payment_method TO method_used, RENAME COLUMN payment_date TO date_paid, RENAME COLUMN transaction_id TO txn_code;
ALTER TABLE payment CHANGE COLUMN amount total_amount DECIMAL(10,2), CHANGE COLUMN booking_id booking_ref INT, CHANGE COLUMN notes remarks VARCHAR(500), CHANGE COLUMN date_paid paid_on DATE, CHANGE COLUMN created_at txn_time TIMESTAMP;




